### PR TITLE
update environment command for Pype

### PR DESCRIPTION
**Pull request by antirotor**
## Feature:
This adds new command - `update-environment`. When run, it will iterate over all packages installed in pype's virtual env (`PYPE_ENV2`) and update them to latest available version.

If followed with `update-requirements` it will write down those new versions to `pypeapp/requirements.txt`.

## Caveats:
It will update all packages to latest version and therefor can introduce unsolvable 3rd party incompatibilities.

## Usage:

To fully update packages:
```
pype update-environment
pype update-requirements
```

🏳️ **Relates to:** pypeclub/pype#484
|---|

### CODE REVIEW

**Review by jezscha — COMMENTED** [review]
wouldn't we want to use something like this tool for validating against those conflicts? https://pypi.org/project/pip-conflict-checker/

**Comment by antirotor** [comment]
I think main problem is not **detection** of conflicts - this by my test is usually catched by pip itself. But updating whole environment will be most likely unsuccessful most of the times because we use so many packages. Good example is updating `setuptools` - in latest version `distutils` are deprecated and because of this `OpenTimelineIO` will not build.

**Review by jezscha — CHANGES_REQUESTED** [review]
we need to thing this trough as for some cases we need to hold freeze versions for some dependencies (nuke needs some because of compatibility to python 2.7)

**Comment by mkolar** [comment]
I'm also not sure this is need or in fact helpful much. It's a bit of an alchemy to get the versions of everything just right and this kind of throws a bomb into it :)

**Pull request closed without merging**
